languageCode = 'en-ca'
title = 'DATA 3464'
enableGitInfo = true
baseURL = "https://mru-data3464.github.io/w26/"
copyright = "Â© Charlotte Curtis 2026 | Created using <a href='https://github.com/alex-shpak/hugo-book'>Hugo Book Theme</a>" 
enableEmoji = true

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[params]
  BookSection = '*'
  BookTheme = 'auto'
  BookLogo = 'mru_chevron.svg'
  BookFavicon = 'mru_chevron.svg'
  BookComments = false

[markup.tableOfContents]
  startLevel = 2

[[menu.after]]
  pre = "<span style='margin-top:2em; margin-left:2em;'><img src='/img/github-mark-white.svg' style='height: 1.5em;'>&nbsp"
  post = "</span>"
  name = "GitHub Repo (issues etc)"
  url = "https://github.com/mru-data3464/w26"
  weight = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true